### PR TITLE
Pull `llvm/llvm-project` master into master

### PR DESCRIPTION
**Pull request by GeorgeLyon**

### CODE REVIEW

**Comment by mikeurbach** [comment]
Looks like a fast-forward, going to merge.

**Comment by mikeurbach** [comment]
Screenshot from 2020-11-23 08-59-09

Hmm, I see this PR wants to add 1431 commits, which appears to be exactly the difference in upstream llvm/llvm-project: https://github.com/llvm/llvm-project/compare/d50149b...95956c1. Not sure why GitHub won't "Rebase and Merge" these. I'd prefer to not put merge commits into the history if they're unnecessary, so let me see if I can just push the fast-forward from the CLI.

**Comment by mikeurbach** [comment]
done
```
To github.com:circt/llvm.git                                                                                                                                                                                       
   d50149b42ec..95956c1c9aa  master -> master
```

**Comment by GeorgeLyon** [comment]
>  Not sure why GitHub won't "Rebase and Merge" these

I think this is related to why I couldn't come up with a merge base without some finagling, but the root cause of that is still a mystery to me.

Thanks @mikeurbach!

**Pull request merged**
