### PR TITLE
Update main to latest LLVM main

### PR DESCRIPTION
**Pull request by youngar**

### CODE REVIEW

**Comment by youngar** [comment]
This updates the main branch, not the master branch like we have done in the past.

**Comment by lattner** [comment]
Thank you for doing this, switching master -> main makes sense!  Is that why this has 5000 files changed?  I'm not sure how to review this, so if it others think this is the right thing, go for it.

**Comment by stephenneuendorffer** [comment]
I don't think we need pull requests to update the circt/llvm repo.  Just feel free to push commits.   The corresponding llvm/circt update should have a pull request, though.

**Comment by youngar** [comment]
I don't think I have the ability to push changes directly or merge this PR.  Are we supposed to be able to gain permission once we are apart of the LLVM organization?

I also just noticed that there is a workflow for syncing the main branch https://github.com/circt/llvm/actions?query=workflow%3A%22main+branch+sync%22. Is this what I should be using?

**Comment by stephenneuendorffer** [comment]
@youngar I committed the PR and gave you access permissions to the repo.  I believe the workflow is set up to synchronize the main and master branch.  It can probably go away now that almost everything has switched to the main branch.

**Comment by youngar** [comment]
Thanks @stephenneuendorffer!

**Pull request merged**
